AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: main_table
      AttributeDefinitions:
        - 
          AttributeName: record_type
          AttributeType: S
        - 
          AttributeName: id
          AttributeType: S
        - 
          AttributeName: school_id
          AttributeType: S
      KeySchema:
        - 
          AttributeName: record_type
          KeyType: HASH
        - 
          AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - 
          IndexName: school_id_index
          KeySchema:
            - 
              AttributeName: school_id
              KeyType: HASH
            - 
              AttributeName: record_type
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
    

  FastJukuBackend:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: arn:aws:iam::133507509735:role/lambda-apigateway-role
      Events:
        GetRoot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
        PostRoot:
          Type: Api
          Properties:
            Path: /
            Method: post
        CreateTeacher:
          Type: Api
          Properties:
            Path: /teachers
            Method: post
        ListTeachers:
          Type: Api
          Properties:
            Path: /teachers/
            Method: get
        GetTeacher:
          Type: Api
          Properties:
            Path: /teachers/{teacher_id}
            Method: get
        UpdateTeacher:
          Type: Api
          Properties:
            Path: /teachers/{teacher_id}
            Method: put
        DeleteTeacher:
          Type: Api
          Properties:
            Path: /teachers/{teacher_id}
            Method: delete
        CreateMeta:
          Type: Api
          Properties:
            Path: /metas
            Method: post
        ListMetas:
          Type: Api
          Properties:
            Path: /metas
            Method: get
        GetMeta:
          Type: Api
          Properties:
            Path: /metas/{school_id}
            Method: get
        UpdateMeta:
          Type: Api
          Properties:
            Path: /metas/{school_id}
            Method: put
        DeleteMeta:
          Type: Api
          Properties:
            Path: /metas/{school_id}
            Method: delete
        CreateTimeslot:
          Type: Api
          Properties:
            Path: /timeslots
            Method: post
        CalculateTimeslot:
          Type: Api
          Properties:
            Path: /timeslots/{school_id}/calculate
            Method: post
        Docs:
          Type: Api
          Properties:
            Path: /docs
            Method: get
        DocsJson:
          Type: Api
          Properties:
            Path: /openapi.json
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.11-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FastJukuBackendApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
