AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MainTable
      AttributeDefinitions:
        - AttributeName: UID
          AttributeType: S
        - AttributeName: Type
          AttributeType: S
        - AttributeName: GivenName
          AttributeType: S
        - AttributeName: FamilyName
          AttributeType: S
        - AttributeName: DisplayName
          AttributeType: S
        - AttributeName: SchoolName
          AttributeType: S
        - AttributeName: ClassHourlyPay
          AttributeType: N
        - AttributeName: OfficeHourlyPay
          AttributeType: N
        - AttributeName: OfficeWorkTime
          AttributeType: N
        - AttributeName: AvailableSubjects
          AttributeType: SS
        - AttributeName: AvailableTimeslots
          AttributeType: SS  
        - AttributeName: ClassStudent1UID
          AttributeType: S
        - AttributeName: ClassStudent2UID
          AttributeType: S
        - AttributeName: ClassSubject1
          AttributeType: S
        - AttributeName: ClassSubject2
          AttributeType: S
        - AttributeName: InstructorUID
          AttributeType: S

      KeySchema:
        - AttributeName: UID
          KeyType: HASH
        - AttributeName: Type
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  FastJukuBackend:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: arn:aws:iam::133507509735:role/lambda-apigateway-role
      Events:
        Root:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
        Docs:
          Type: Api
          Properties:
            Path: /docs
            Method: get
        DocsJson:
          Type: Api
          Properties:
            Path: /openapi.json
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.11-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FastJukuBackendApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
